# Generated by Django 5.2.13 on 2026-09-07 16:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0001_personal_models'),
        ('personal', '0004_invocation_usage'),
        ('tenancy', '0001_personal_context'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalGatewayRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_id', models.CharField(max_length=64)),
                ('request_digest', models.CharField(max_length=64)),
                ('requested_model', models.CharField(max_length=255)),
                ('router', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='routers.router')),
                ('source_ids', models.JSONField(default=list)),
                ('state', models.CharField(default='pending', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.project')),
                ('result_log', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gateway.gatewayrequestlog')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'constraints': [
                    models.UniqueConstraint(fields=('tenant', 'request_id'), name='personal_gateway_request_unique'),
                ],
            },
        ),
        migrations.CreateModel(
            name='PersonalGatewayAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_id', models.UUIDField()),
                ('state', models.CharField(default='dispatched', max_length=16)),
                ('total_tokens', models.PositiveBigIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('dispatched_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='personal.personalgatewayrequest')),
            ],
            options={
                'constraints': [
                    models.UniqueConstraint(fields=('request', 'source_id'), name='personal_gateway_attempt_unique'),
                ],
            },
        ),
    ]
