# Generated by Django 5.2.13 on 2026-09-08 05:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_personal_context'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('deleted', 'Deleted')], default='active', max_length=32)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metric', models.CharField(max_length=128)),
                ('threshold', models.CharField(max_length=64)),
                ('threshold_value', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('threshold_unit', models.CharField(blank=True, max_length=16)),
                ('operator', models.CharField(choices=[('gt', '>'), ('gte', '>='), ('lt', '<'), ('lte', '<='), ('eq', '=')], default='gte', max_length=16)),
                ('resource_type', models.CharField(blank=True, max_length=64)),
                ('resource_id', models.CharField(blank=True, max_length=128)),
                ('window_seconds', models.PositiveIntegerField(default=300)),
                ('cooldown_seconds', models.PositiveIntegerField(default=300)),
                ('notification_channels', models.JSONField(blank=True, default=dict)),
                ('last_evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=64)),
                ('muted_until', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_alert_rules', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='tenancy.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='tenancy.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'metric', 'status'], name='metrics_ale_tenant__bbb69f_idx'), models.Index(fields=['tenant', 'resource_type', 'resource_id', 'status'], name='metrics_ale_tenant__7dcf70_idx')],
            },
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('firing', 'Firing'), ('resolved', 'Resolved'), ('deleted', 'Deleted')], default='firing', max_length=32)),
                ('metric', models.CharField(max_length=128)),
                ('resource_type', models.CharField(blank=True, max_length=64)),
                ('resource_id', models.CharField(blank=True, max_length=128)),
                ('value', models.DecimalField(decimal_places=6, max_digits=24)),
                ('threshold_value', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('threshold', models.CharField(blank=True, max_length=64)),
                ('triggered_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('is_test', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_events', to='tenancy.tenant')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='metrics.alertrule')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'status', 'triggered_at'], name='metrics_ale_tenant__fb5f00_idx'), models.Index(fields=['tenant', 'rule', 'status'], name='metrics_ale_tenant__467acb_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_test', False), ('status', 'firing')), fields=('rule',), name='metrics_one_open_incident')],
            },
        ),
        migrations.CreateModel(
            name='MetricSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('deleted', 'Deleted')], default='active', max_length=32)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('resource_type', models.CharField(choices=[('api_key', 'API key'), ('model', 'Model'), ('agent', 'Agent'), ('dataset', 'Dataset'), ('router', 'Router'), ('system', 'System')], max_length=64)),
                ('resource_id', models.CharField(blank=True, max_length=128)),
                ('metrics_json', models.JSONField(blank=True, default=dict)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_snapshots', to='tenancy.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'resource_type', 'resource_id', 'captured_at'], name='metrics_met_tenant__b1318e_idx'), models.Index(fields=['tenant', 'captured_at'], name='metrics_met_tenant__007d54_idx')],
            },
        ),
        migrations.CreateModel(
            name='MonitoringHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(max_length=32)),
                ('last_started_at', models.DateTimeField(null=True)),
                ('last_success_at', models.DateTimeField(null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=64)),
                ('lease_until', models.DateTimeField(null=True)),
                ('lease_id', models.CharField(blank=True, max_length=36)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant', 'component'), name='metrics_heartbeat_component')],
            },
        ),
        migrations.CreateModel(
            name='AlertNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('deleted', 'Deleted')], default='active', max_length=32)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_key', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('lease_id', models.CharField(blank=True, max_length=36)),
                ('channel', models.CharField(choices=[('email', 'Email')], default='email', max_length=32)),
                ('target', models.CharField(max_length=256)),
                ('phase', models.CharField(default='firing', max_length=16)),
                ('delivery_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('deleted', 'Deleted')], default='pending', max_length=32)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='metrics.alertevent')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_notifications', to='tenancy.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'delivery_status', 'created_at'], name='metrics_ale_tenant__9a8cbc_idx'), models.Index(fields=['tenant', 'event', 'channel'], name='metrics_ale_tenant__b4dc16_idx'), models.Index(fields=['tenant', 'delivery_status', 'next_attempt_at'], name='metrics_alert_outbox_due')],
            },
        ),
    ]
