# Generated by Django 5.2.13 on 2026-09-07 15:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deployments', '0002_personal_models'),
        ('routers', '0001_personal_models'),
        ('tenancy', '0001_personal_context'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GatewayRequestLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_id', models.CharField(blank=True, max_length=128)),
                ('model', models.CharField(max_length=255)),
                ('operation', models.CharField(default='chat.completions', max_length=32)),
                ('image_count', models.PositiveIntegerField(default=0)),
                ('router_strategy', models.CharField(blank=True, max_length=32)),
                ('routing_trace', models.JSONField(blank=True, default=dict)),
                ('provider', models.CharField(blank=True, max_length=64)),
                ('request_tokens', models.PositiveIntegerField(default=0)),
                ('response_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=32)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('fallback_count', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gateway_request_logs', to=settings.AUTH_USER_MODEL)),
                ('consumer_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumer_gateway_request_logs', to='deployments.deployment')),
                ('deployment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gateway_request_logs', to='deployments.deployment')),
                ('router', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gateway_request_logs', to='routers.router')),
                ('selected_model_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gateway_request_logs', to='deployments.modelgroup')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gateway_request_logs', to='tenancy.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='GatewayImageOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('principal', models.CharField(max_length=80)),
                ('key_digest', models.CharField(max_length=64)),
                ('request_digest', models.CharField(max_length=64)),
                ('state', models.CharField(default='pending', max_length=16)),
                ('operation', models.CharField(max_length=32)),
                ('asset_ids', models.JSONField(default=list)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant')),
                ('gateway_log', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gateway.gatewayrequestlog')),
            ],
        ),
        migrations.AddIndex(
            model_name='gatewayrequestlog',
            index=models.Index(fields=['tenant', 'created_at'], name='gateway_gat_tenant__f6461a_idx'),
        ),
        migrations.AddIndex(
            model_name='gatewayrequestlog',
            index=models.Index(fields=['tenant', 'model', 'created_at'], name='gateway_gat_tenant__f7d868_idx'),
        ),
        migrations.AddIndex(
            model_name='gatewayrequestlog',
            index=models.Index(fields=['tenant', 'router', 'created_at'], name='gateway_gat_tenant__9092c9_idx'),
        ),
        migrations.AddIndex(
            model_name='gatewayrequestlog',
            index=models.Index(fields=['tenant', 'status', 'created_at'], name='gateway_gat_tenant__a0edb8_idx'),
        ),
        migrations.AddConstraint(
            model_name='gatewayimageoperation',
            constraint=models.UniqueConstraint(fields=('tenant', 'principal', 'key_digest'), name='gateway_image_idempotency'),
        ),
    ]
