# Generated by Django 5.2.13 on 2026-10-04 13:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobile", "0002_mobilecommand_result_receipt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mobilecommand",
            name="action",
            field=models.CharField(
                choices=[
                    ("observe", "Observe"),
                    ("tap_text", "Tap text"),
                    ("tap_coordinates", "Tap coordinates"),
                    ("type_text", "Type text"),
                    ("swipe", "Swipe"),
                    ("press_back", "Press back"),
                    ("open_app", "Open app"),
                    ("wait_for_state", "Wait for state"),
                    ("capture_screen", "Capture screen"),
                    ("press_home", "Home"),
                    ("press_recents", "Recent apps"),
                    ("long_press", "Long press"),
                ],
                max_length=64,
            ),
        ),
        migrations.CreateModel(
            name="MobileVideoSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("owner_subject_hash", models.CharField(max_length=64)),
                ("pairing_hash", models.CharField(max_length=64)),
                ("state", models.CharField(default="pending", max_length=24)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("expires_at", models.DateTimeField()),
                ("viewer_seen_at", models.DateTimeField()),
                ("device_seen_at", models.DateTimeField(null=True)),
                ("geometry", models.JSONField(default=dict)),
                ("geometry_version", models.PositiveIntegerField(default=0)),
                ("signals", models.JSONField(default=list)),
                ("sequence", models.PositiveIntegerField(default=0)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_sessions",
                        to="mobile.mobiledevice",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["device", "state", "expires_at"],
                        name="mobile_video_active_idx",
                    )
                ],
            },
        ),
    ]
