# Generated by Django 5.2.13 on 2026-09-07 18:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0007_router_credentials'),
        ('providers', '0001_personal_models'),
        ('routers', '0001_personal_models'),
        ('tenancy', '0001_personal_context'),
        ('workspaces', '0001_personal_runtime'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceToolManagedProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('deleted', 'Deleted')], default='active', max_length=32)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('tool', models.CharField(default='codex', max_length=32)),
                ('profile', models.CharField(default='nexus', max_length=64)),
                ('managed_mcp_servers', models.JSONField(blank=True, default=dict)),
                ('config_revision', models.CharField(blank=True, max_length=64)),
                ('last_backup_path', models.CharField(blank=True, max_length=1024)),
                ('last_backup_at', models.DateTimeField(blank=True, null=True)),
                ('last_applied_at', models.DateTimeField(blank=True, null=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_profiles', to='workspaces.workspaceconnection')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workspace_tool_profiles', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspace_tool_profiles', to='tenancy.project')),
                ('provider_runtime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspace_tool_profiles', to='providers.providerruntimeaccount')),
                ('router', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspace_tool_profiles', to='routers.router')),
                ('router_credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspace_tool_profiles', to='personal.personalroutercredential')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_tool_profiles', to='tenancy.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'project', 'status'], name='workspaces__tenant__23f5ac_idx'), models.Index(fields=['connection', 'tool', 'profile'], name='workspaces__connect_8890f0_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('connection', 'tool', 'profile'), name='unique_active_workspace_tool_profile')],
            },
        ),
    ]
