# Generated by Django 5.2.13 on 2026-09-07 12:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deployments', '0001_personal_models'),
        ('tenancy', '0001_personal_context'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('deleted', 'Deleted')], default='active', max_length=32)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.SlugField(max_length=64, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProviderAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('deleted', 'Deleted')], default='active', max_length=32)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('account_id', models.CharField(max_length=128)),
                ('url', models.URLField(blank=True, max_length=1024)),
                ('encrypted_key', models.TextField(blank=True)),
                ('encrypted_username', models.TextField(blank=True)),
                ('encrypted_password', models.TextField(blank=True)),
                ('auth_mode', models.CharField(choices=[('api_key', 'API Key'), ('interactive_login', 'Interactive Login'), ('username_password_login', 'Username Password Login')], default='api_key', max_length=32)),
                ('preferred_runtime_type', models.CharField(blank=True, choices=[('codex_proxy', 'Codex Proxy'), ('cliproxyapi', 'CLIProxyAPI')], max_length=32)),
                ('login_status', models.CharField(choices=[('unknown', 'Unknown'), ('login_required', 'Login Required'), ('logging_in', 'Logging In'), ('active', 'Active'), ('failed', 'Failed')], default='unknown', max_length=32)),
                ('last_login_error', models.CharField(blank=True, max_length=512)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('pricing_rate', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('quota_status', models.CharField(choices=[('unknown', 'Unknown'), ('available', 'Available'), ('limited', 'Limited'), ('exhausted', 'Exhausted')], default='unknown', max_length=32)),
                ('quota_reset_at', models.DateTimeField(blank=True, null=True)),
                ('quota_remaining_tokens', models.PositiveBigIntegerField(blank=True, null=True)),
                ('quota_remaining_requests', models.PositiveBigIntegerField(blank=True, null=True)),
                ('last_quota_error', models.CharField(blank=True, max_length=512)),
                ('last_quota_checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_provider_accounts', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='providers.provider')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_accounts', to='tenancy.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'provider', 'status'], name='providers_p_tenant__28faeb_idx'), models.Index(fields=['tenant', 'account_id', 'status'], name='providers_p_tenant__1d2833_idx'), models.Index(fields=['tenant', 'quota_status', 'quota_reset_at'], name='providers_p_tenant__4a9010_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'provider', 'account_id'), name='unique_provider_account')],
            },
        ),
        migrations.CreateModel(
            name='ProviderImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_subject_hash', models.CharField(max_length=64)),
                ('context_project_id', models.CharField(blank=True, max_length=36)),
                ('request_key', models.UUIDField()),
                ('content_hash', models.CharField(max_length=64)),
                ('duplicate_mode', models.CharField(default='skip', max_length=8)),
                ('encrypted_payload', models.TextField(blank=True)),
                ('results', models.JSONField(default=list)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(default='preview', max_length=16)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_imports', to='tenancy.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant', 'owner_subject_hash', 'request_key'), name='provider_import_request_unique')],
            },
        ),
        migrations.CreateModel(
            name='ProviderRuntimeAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('starting', 'Starting'), ('stopping', 'Stopping'), ('login_required', 'Login Required'), ('active', 'Active'), ('unhealthy', 'Unhealthy'), ('stopped', 'Stopped'), ('failed', 'Failed'), ('deleted', 'Deleted')], default='created', max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('runtime_type', models.CharField(choices=[('direct_api', 'Direct API'), ('codex_proxy', 'Codex Proxy'), ('cliproxyapi', 'CLIProxyAPI')], max_length=32)),
                ('share_mode', models.CharField(choices=[('private', 'Private'), ('shared_pool', 'Shared Pool')], default='private', max_length=32)),
                ('container_id', models.CharField(blank=True, max_length=255)),
                ('internal_login_url', models.URLField(blank=True, max_length=1024)),
                ('internal_api_url', models.URLField(blank=True, max_length=1024)),
                ('public_login_path', models.CharField(blank=True, max_length=1024)),
                ('encrypted_proxy_api_key', models.TextField(blank=True)),
                ('storage_path', models.CharField(blank=True, max_length=1024)),
                ('last_error', models.CharField(blank=True, max_length=1024)),
                ('last_health_check_at', models.DateTimeField(blank=True, null=True)),
                ('quota_snapshot', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_runtime_accounts', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_runtime_accounts', to='tenancy.project')),
                ('provider_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runtime_accounts', to='providers.provideraccount')),
                ('source_provider_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_runtime_accounts', to='providers.provideraccount')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_runtime_accounts', to='tenancy.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'runtime_type', 'status'], name='providers_p_tenant__0cc5b2_idx'), models.Index(fields=['tenant', 'share_mode', 'status'], name='providers_p_tenant__41ca48_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('source_provider_account__isnull', False), models.Q(('status', 'deleted'), _negated=True)), fields=('source_provider_account',), name='unique_active_runtime_per_provider_account')],
            },
        ),
        migrations.CreateModel(
            name='ProviderRuntimeHealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Created'), ('starting', 'Starting'), ('stopping', 'Stopping'), ('login_required', 'Login Required'), ('active', 'Active'), ('unhealthy', 'Unhealthy'), ('stopped', 'Stopped'), ('failed', 'Failed'), ('deleted', 'Deleted')], max_length=32)),
                ('reason', models.CharField(blank=True, max_length=1024)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('runtime_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_checks', to='providers.providerruntimeaccount')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_runtime_health_checks', to='tenancy.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'status', 'checked_at'], name='providers_p_tenant__a1a79c_idx'), models.Index(fields=['runtime_account', 'checked_at'], name='providers_p_runtime_d676d2_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProviderRuntimeModelOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('image_pricing', models.JSONField(blank=True, default=list)),
                ('upstream_model_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('detected', 'Detected'), ('confirmed', 'Confirmed'), ('unavailable', 'Unavailable'), ('disabled', 'Disabled'), ('deleted', 'Deleted')], default='detected', max_length=32)),
                ('price_per_1k_tokens', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('input_price_per_1k_tokens', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('output_price_per_1k_tokens', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('cached_input_price_per_1k_tokens', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('reasoning_output_price_per_1k_tokens', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('daily_limit', models.PositiveIntegerField(default=0)),
                ('monthly_limit', models.PositiveIntegerField(default=0)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('capabilities', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('health_status', models.CharField(choices=[('unknown', 'Unknown'), ('healthy', 'Healthy'), ('degraded', 'Degraded'), ('unhealthy', 'Unhealthy')], default='unknown', max_length=32)),
                ('health_reason', models.CharField(blank=True, max_length=512)),
                ('last_discovered_at', models.DateTimeField(blank=True, null=True)),
                ('last_health_check_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('canonical_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provider_offers', to='deployments.canonicalmodel')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_provider_model_offers', to=settings.AUTH_USER_MODEL)),
                ('runtime_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_offers', to='providers.providerruntimeaccount')),
            ],
            options={
                'indexes': [models.Index(fields=['runtime_account', 'status'], name='providers_p_runtime_75e32f_idx'), models.Index(fields=['canonical_model', 'status'], name='providers_p_canonic_542b5c_idx'), models.Index(fields=['health_status', 'status'], name='providers_p_health__2d962a_idx')],
                'constraints': [models.UniqueConstraint(fields=('runtime_account', 'upstream_model_id'), name='unique_runtime_upstream_model'), models.UniqueConstraint(condition=models.Q(('canonical_model__isnull', False), ('status__in', ['confirmed', 'unavailable'])), fields=('runtime_account', 'canonical_model'), name='unique_runtime_canonical_model')],
            },
        ),
    ]
