from django.urls import path
from .callback_views import (
    InternalAgentRunContextExchangeView,
    InternalInvocationUsageView,
    InternalAgentWorkspaceFilesView,
    InternalAgentWorkspaceFileReadView,
    InternalAgentWorkspaceFileWriteView,
    InternalAgentWorkspaceCommandRunView,
    InternalInvocationWorkspaceView,
    InternalInvocationTerminalView,
    InternalInvocationMemoryView,
    InternalInvocationMemoryDetailView,
    InternalInvocationConnectionListView,
    InternalInvocationConnectionDetailView,
    InternalInvocationConnectionTestView,
    InternalInvocationConnectionValidateView,
    InternalInvocationBindingView,
    InternalInvocationMobileView,
    InternalInvocationBrowserView,
    InternalInvocationMobileCommandView,
    InternalRunInteractionListView,
    InternalRunInteractionDetailView,
    InternalRunContextView,
    InternalRunControlView,
    InternalRunCheckpointView,
    InternalRunOperationView,
    InternalRunDisplayAssetView,
)

urlpatterns = [
    path(
        "internal/agent-run-contexts/<uuid:grant_id>/exchange/",
        InternalAgentRunContextExchangeView.as_view(),
        name="internal-agent-run-context-exchange",
    ),
    path("internal/agent-workspaces/<uuid:runtime_id>/files/", InternalAgentWorkspaceFilesView.as_view(), name="internal-agent-workspace-files"),
    path("internal/agent-workspaces/<uuid:runtime_id>/files/read/", InternalAgentWorkspaceFileReadView.as_view(), name="internal-agent-workspace-file-read"),
    path("internal/agent-workspaces/<uuid:runtime_id>/files/write/", InternalAgentWorkspaceFileWriteView.as_view(), name="internal-agent-workspace-file-write"),
    path("internal/agent-workspaces/<uuid:runtime_id>/commands/run/", InternalAgentWorkspaceCommandRunView.as_view(), name="internal-agent-workspace-command-run"),
    path("internal/agent-runs/<uuid:run_id>/workspace/", InternalInvocationWorkspaceView.as_view(), name="internal-agent-run-workspace"),
    path("internal/agent-runs/<uuid:run_id>/terminal/", InternalInvocationTerminalView.as_view(), name="internal-agent-run-terminal"),
    path("internal/agent-runs/<uuid:run_id>/usage/", InternalInvocationUsageView.as_view(), name="internal-agent-run-usage"),
    path("internal/agent-runs/<uuid:run_id>/memory/", InternalInvocationMemoryView.as_view(), name="internal-agent-run-memory"),
    path("internal/agent-runs/<uuid:run_id>/mobile/", InternalInvocationMobileView.as_view(), name="internal-agent-run-mobile"),
    path("internal/agent-runs/<uuid:run_id>/browser/", InternalInvocationBrowserView.as_view(), name="internal-agent-run-browser"),
    path("internal/agent-runs/<uuid:run_id>/mobile/commands/<uuid:command_id>/", InternalInvocationMobileCommandView.as_view(), name="internal-agent-run-mobile-command"),
    path(
        "internal/agent-runs/<uuid:run_id>/memory/<uuid:memory_id>/",
        InternalInvocationMemoryDetailView.as_view(),
        name="internal-agent-run-memory-detail",
    ),
    path("internal/agent-runs/<uuid:run_id>/manage/connections/", InternalInvocationConnectionListView.as_view(), name="internal-agent-run-connections"),
    path("internal/agent-runs/<uuid:run_id>/manage/connections/validate/", InternalInvocationConnectionValidateView.as_view(), name="internal-agent-run-connection-validate"),
    path("internal/agent-runs/<uuid:run_id>/manage/connections/<uuid:connection_id>/", InternalInvocationConnectionDetailView.as_view(), name="internal-agent-run-connection-detail"),
    path("internal/agent-runs/<uuid:run_id>/manage/connections/<uuid:connection_id>/test/", InternalInvocationConnectionTestView.as_view(), name="internal-agent-run-connection-test"),
    path("internal/agent-runs/<uuid:run_id>/manage/bindings/", InternalInvocationBindingView.as_view(), name="internal-agent-run-bindings"),
    path("internal/agent-runs/<uuid:run_id>/interactions/", InternalRunInteractionListView.as_view(), name="internal-agent-run-interactions"),
    path("internal/agent-runs/<uuid:run_id>/interactions/<uuid:interaction_id>/", InternalRunInteractionDetailView.as_view(), name="internal-agent-run-interaction-detail"),
    path("internal/agent-runs/<uuid:run_id>/context/", InternalRunContextView.as_view(), name="internal-agent-run-context"),
    path("internal/agent-runs/<uuid:run_id>/checkpoint/", InternalRunCheckpointView.as_view(), name="internal-agent-run-checkpoint"),
    path("internal/agent-runs/<uuid:run_id>/operations/", InternalRunOperationView.as_view(), name="internal-agent-run-operations"),
    path("internal/agent-runs/<uuid:run_id>/operations/<uuid:operation_id>/", InternalRunOperationView.as_view(), name="internal-agent-run-operation-detail"),
    path("internal/agent-runs/<uuid:run_id>/control/", InternalRunControlView.as_view(), name="internal-agent-run-control"),
    path("internal/agent-runs/<uuid:run_id>/display-assets/", InternalRunDisplayAssetView.as_view(), name="internal-agent-run-display-assets"),
    path("internal/agent-runs/<uuid:run_id>/display-assets/<uuid:asset_id>/", InternalRunDisplayAssetView.as_view(), name="internal-agent-run-image"),
]
