"""Shared operational Edge API, without hosted commercial route composition."""
from django.urls import path
from .edge_views import (
    AgentEdgeBindingView,
    EdgeAgentRegistrationListView,
    EdgeAgentManagedResumeView,
    EdgeDeviceAgentRegistrationDetailView,
    EdgeDeviceAgentRegistrationView,
    EdgeDeviceCertificateRenewView,
    EdgeDeviceCertificateConfirmView,
    EdgeIngressCertificateRenewView,
    EdgeDevicePresenceView,
    EdgeJWKSView,
    EdgeNodeEnrollView,
    EdgeNodeDetailView,
    EdgeNodeListView,
    EdgeNodeRevokeView,
    EdgePairingCodeCreateView,
    EdgeRouterCapabilitiesView,
    EdgeRelayServiceView,
    EdgeRelayAssignmentView,
    EdgeRelayConfigurationView,
)

urlpatterns = [
    path("edge/.well-known/jwks.json", EdgeJWKSView.as_view(), name="edge-jwks"),
    path("edge/pairing-codes/", EdgePairingCodeCreateView.as_view(), name="edge-pairing-code-create"),
    path("edge/capabilities/", EdgeRouterCapabilitiesView.as_view(), name="edge-router-capabilities"),
    path("edge/relay-service/", EdgeRelayServiceView.as_view(), name="edge-relay-service"),
    path("edge/nodes/", EdgeNodeListView.as_view(), name="edge-node-list"),
    path("edge/nodes/enroll/", EdgeNodeEnrollView.as_view(), name="edge-node-enroll"),
    path("edge/nodes/<uuid:node_id>/", EdgeNodeDetailView.as_view(), name="edge-node-detail"),
    path("edge/nodes/<uuid:node_id>/revoke/", EdgeNodeRevokeView.as_view(), name="edge-node-revoke"),
    path("edge/v1/device-certificate/renew/", EdgeDeviceCertificateRenewView.as_view(), name="edge-device-certificate-renew"),
    path("edge/v1/device-certificate/confirm/", EdgeDeviceCertificateConfirmView.as_view(), name="edge-device-certificate-confirm"),
    path("edge/v1/ingress-certificate/renew/", EdgeIngressCertificateRenewView.as_view(), name="edge-ingress-certificate-renew"),
    path("edge/v1/presence/", EdgeDevicePresenceView.as_view(), name="edge-device-presence"),
    path("edge/v1/relay-assignment/", EdgeRelayAssignmentView.as_view(), name="edge-relay-assignment"),
    path("edge/v1/relay-configuration/", EdgeRelayConfigurationView.as_view(), name="edge-relay-configuration"),
    path("edge/agent-registrations/", EdgeAgentRegistrationListView.as_view(), name="edge-agent-registration-list"),
    path(
        "edge/agent-registrations/<uuid:registration_id>/resume-managed/",
        EdgeAgentManagedResumeView.as_view(),
        name="edge-agent-registration-resume-managed",
    ),
    path("edge/v1/agent-registrations/", EdgeDeviceAgentRegistrationView.as_view(), name="edge-device-agent-registration"),
    path("edge/v1/agent-registrations/<uuid:registration_id>/", EdgeDeviceAgentRegistrationDetailView.as_view(), name="edge-device-agent-registration-detail"),
    path("agents/<uuid:agent_id>/runtime/edge-binding/", AgentEdgeBindingView.as_view(), name="agent-edge-binding"),
]
