# Generated by Django 5.2.13 on 2026-07-04 06:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('project_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('action', models.CharField(db_index=True, max_length=128)),
                ('resource_type', models.CharField(blank=True, max_length=128)),
                ('resource_id', models.CharField(blank=True, max_length=128)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['tenant_id', 'action', 'created_at'], name='audit_audit_tenant__5369fc_idx'), models.Index(fields=['tenant_id', 'actor', 'created_at'], name='audit_audit_tenant__4bbf4e_idx')],
            },
        ),
    ]
