# Generated by Django 5.2.13 on 2026-09-08 09:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_personal_context'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CanonicalModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('deleted', 'Deleted')], default='active', max_length=32)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('key', models.SlugField(max_length=128, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('family', models.CharField(blank=True, max_length=128)),
                ('modalities', models.JSONField(blank=True, default=list)),
                ('input_modalities', models.JSONField(blank=True, default=list)),
                ('output_modalities', models.JSONField(blank=True, default=list)),
                ('operations', models.JSONField(blank=True, default=list)),
                ('capabilities', models.JSONField(blank=True, default=list)),
                ('context_window', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['key'],
                'indexes': [models.Index(fields=['status', 'key'], name='deployments_status_886002_idx')],
            },
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('deleted', 'Deleted')], default='active', max_length=32)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deployment_id', models.CharField(max_length=128)),
                ('upstream_model_id', models.CharField(max_length=255)),
                ('endpoint', models.URLField(blank=True, max_length=1024)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('tenant', 'Tenant'), ('team', 'Team'), ('project', 'Project')], default='tenant', max_length=32)),
                ('pricing_rate', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('health_status', models.CharField(choices=[('unknown', 'Unknown'), ('healthy', 'Healthy'), ('degraded', 'Degraded'), ('unhealthy', 'Unhealthy')], default='unknown', max_length=32)),
                ('health_reason', models.CharField(blank=True, max_length=512)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_failure_at', models.DateTimeField(blank=True, null=True)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('last_latency_ms', models.PositiveIntegerField(default=0)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('canonical_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sources', to='deployments.canonicalmodel')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_deployments', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployments', to='tenancy.project')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployments', to='tenancy.team')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='tenancy.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'status'], name='deployments_tenant__281d38_idx'), models.Index(fields=['tenant', 'health_status'], name='deployments_tenant__bab5e8_idx'), models.Index(fields=['tenant', 'visibility', 'status'], name='deployments_tenant__a4244b_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'deployment_id'), name='unique_tenant_deployment_id')],
            },
        ),
        migrations.CreateModel(
            name='DeploymentHealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('unknown', 'Unknown'), ('healthy', 'Healthy'), ('degraded', 'Degraded'), ('unhealthy', 'Unhealthy')], max_length=32)),
                ('reason', models.CharField(blank=True, max_length=512)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_checks', to='deployments.deployment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployment_health_checks', to='tenancy.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'status', 'checked_at'], name='deployments_tenant__3b18b9_idx'), models.Index(fields=['deployment', 'checked_at'], name='deployments_deploym_dcd829_idx')],
            },
        ),
        migrations.CreateModel(
            name='ModelGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('deleted', 'Deleted')], default='active', max_length=32)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=128)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('tenant', 'Tenant'), ('team', 'Team'), ('project', 'Project')], default='tenant', max_length=32)),
                ('routing_strategy', models.CharField(choices=[('fallback', 'Fallback'), ('best_health', 'Best health'), ('lowest_cost', 'Lowest cost'), ('lowest_latency', 'Lowest latency'), ('weighted', 'Weighted')], default='fallback', max_length=32)),
                ('routing_config', models.JSONField(blank=True, default=dict)),
                ('routing_revision', models.PositiveBigIntegerField(default=1)),
                ('canonical_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_groups', to='deployments.canonicalmodel')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_model_groups', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_groups', to='tenancy.project')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_groups', to='tenancy.team')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_groups', to='tenancy.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'visibility', 'status'], name='deployments_tenant__b3dc0f_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'name'), name='unique_tenant_model_group')],
            },
        ),
        migrations.CreateModel(
            name='ModelGroupDeployment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('deleted', 'Deleted')], default='active', max_length=32)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('weight', models.PositiveIntegerField(default=100)),
                ('fallback_order', models.PositiveIntegerField(default=100)),
                ('last_selected_at', models.DateTimeField(blank=True, null=True)),
                ('selection_count', models.PositiveIntegerField(default=0)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_group_links', to='deployments.deployment')),
                ('model_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployment_links', to='deployments.modelgroup')),
            ],
            options={
                'indexes': [models.Index(fields=['model_group', 'status', 'enabled', 'priority'], name='deployments_model_g_7d00d0_idx')],
                'constraints': [models.UniqueConstraint(fields=('model_group', 'deployment'), name='unique_model_group_deployment')],
            },
        ),
        migrations.CreateModel(
            name='ModelGroupRoutingRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision', models.PositiveBigIntegerField()),
                ('routing_strategy', models.CharField(choices=[('fallback', 'Fallback'), ('best_health', 'Best health'), ('lowest_cost', 'Lowest cost'), ('lowest_latency', 'Lowest latency'), ('weighted', 'Weighted')], max_length=32)),
                ('routing_config', models.JSONField(blank=True, default=dict)),
                ('sources', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_model_group_routing_revisions', to=settings.AUTH_USER_MODEL)),
                ('model_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_revisions', to='deployments.modelgroup')),
            ],
            options={
                'indexes': [models.Index(fields=['model_group', '-revision'], name='deployments_model_g_1ed957_idx')],
                'constraints': [models.UniqueConstraint(fields=('model_group', 'revision'), name='unique_model_group_routing_revision')],
            },
        ),
    ]
