# Generated by Django 5.2.13 on 2026-09-08 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deployments', '0001_personal_models'),
        ('providers', '0001_personal_models'),
        ('tenancy', '0001_personal_context'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='providers.provider'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='provider_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployments', to='providers.provideraccount'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='provider_runtime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sources', to='providers.providerruntimeaccount'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='runtime_model_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sources', to='providers.providerruntimemodeloffer'),
        ),
    ]
