# Unreleased Personal initial schema. Fold dependency-ready fields and indexes
# into table creation; retain cross-app cycles in the second migration.
import apps.agents.models
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_personal_context'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('disabled', 'Disabled'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='draft', max_length=32)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('tenant', 'Tenant'), ('team', 'Team'), ('project', 'Project')], default='private', max_length=32)),
                ('publication_status', models.CharField(choices=[('unpublished', 'Unpublished'), ('published', 'Published'), ('suspended', 'Suspended')], default='unpublished', max_length=32)),
                ('computer_requirement', models.CharField(choices=[('required', 'Required'), ('optional', 'Optional'), ('disabled', 'Disabled')], default='optional', max_length=16)),
                ('workspace_capabilities', models.JSONField(blank=True, default=list)),
                ('mobile_requirement', models.CharField(choices=[('required', 'Required'), ('optional', 'Optional'), ('disabled', 'Disabled')], default='disabled', max_length=16)),
                ('mobile_capabilities', models.JSONField(blank=True, default=list)),
                ('mobile_policy_source', models.CharField(choices=[('sdk', 'SDK defaults'), ('cloud', 'Cloud override')], default='cloud', max_length=16)),
                ('repo_metadata', models.JSONField(blank=True, default=dict)),
                ('current_version', models.CharField(blank=True, max_length=32)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_agents', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='tenancy.project')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='tenancy.team')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='tenancy.tenant')),
            ],
            options={
                'indexes': [
                    models.Index(fields=['tenant', 'status'], name='agents_agen_tenant__0f3a86_idx'),
                    models.Index(fields=['tenant', 'visibility', 'status'], name='agents_agen_tenant__203933_idx'),
                    models.Index(fields=['tenant', 'publication_status', 'status'], name='agents_agen_tenant__965c4d_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='AgentComputerBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('deleted', 'Deleted')], default='active', max_length=32)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('caller_subject_hash', models.CharField(db_index=True, max_length=64)),
                ('caller_principal_type', models.CharField(max_length=32)),
                ('is_default', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computer_bindings', to='agents.agent')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_computer_bindings', to='tenancy.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_computer_bindings', to='tenancy.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='AgentDeployment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('env', models.CharField(default='prod', max_length=64)),
                ('status', models.CharField(choices=[('deploying', 'Deploying'), ('active', 'Active'), ('stopped', 'Stopped'), ('failed', 'Failed')], default='deploying', max_length=32)),
                ('endpoint_url', models.URLField(blank=True, max_length=1024)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='agents.agent')),
                ('deployed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_deployments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [
                    models.Index(fields=['agent', 'env', 'status'], name='agents_agen_agent_i_c3c458_idx'),
                ],
                'constraints': [
                    models.UniqueConstraint(fields=('agent', 'env'), name='unique_agent_env_deployment'),
                ],
            },
        ),
        migrations.CreateModel(
            name='AgentDisplayRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('run_kind', models.CharField(choices=[('invocation', 'Invocation'), ('demo', 'Demo'), ('deployment', 'Deployment'), ('legacy', 'Legacy')], default='legacy', max_length=32)),
                ('caller_principal_type', models.CharField(blank=True, max_length=32)),
                ('caller_principal_id', models.CharField(blank=True, max_length=128)),
                ('caller_subject_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('display_token_hash', models.CharField(blank=True, max_length=64)),
                ('display_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('workspace_root', models.CharField(blank=True, max_length=1024)),
                ('workspace_cwd', models.CharField(default='.', max_length=1024)),
                ('computer_revision', models.PositiveIntegerField(default=0)),
                ('output_root', models.CharField(blank=True, max_length=1024)),
                ('workspace_capabilities_snapshot', models.JSONField(blank=True, default=list)),
                ('workspace_delegate_token_hash', models.CharField(blank=True, max_length=64)),
                ('workspace_delegate_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('browser_delegate_token_hash', models.CharField(blank=True, max_length=64)),
                ('browser_delegate_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('mobile_capabilities_snapshot', models.JSONField(blank=True, default=list)),
                ('mobile_delegate_token_hash', models.CharField(blank=True, max_length=64)),
                ('mobile_delegate_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('interaction_token_hash', models.CharField(blank=True, max_length=64)),
                ('interaction_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('context_token_hash', models.CharField(blank=True, max_length=64)),
                ('context_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('interaction_mode', models.CharField(blank=True, max_length=32)),
                ('follow_up_mode', models.CharField(default='queue', max_length=24)),
                ('follow_up_attachment_protocol', models.PositiveSmallIntegerField(default=0)),
                ('demo_session_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('display_title', models.CharField(blank=True, max_length=80)),
                ('display_title_source', models.CharField(choices=[('pending', 'Pending'), ('agent', 'Agent'), ('derived', 'Derived'), ('user', 'User')], default='pending', max_length=16)),
                ('caller_hidden_at', models.DateTimeField(blank=True, null=True)),
                ('caller_read_completed_at', models.DateTimeField(blank=True, null=True)),
                ('project_context_snapshot', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=32)),
                ('redaction_status', models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('redaction_metadata', models.JSONField(blank=True, default=dict)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('write_token', models.CharField(max_length=128)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='display_runs', to='agents.agent')),
                ('computer_binding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='display_runs', to='agents.agentcomputerbinding')),
                ('consumer_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumed_agent_display_runs', to='tenancy.project')),
                ('consumer_tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumed_agent_display_runs', to='tenancy.tenant')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_display_runs', to='tenancy.tenant')),
            ],
            options={
                'indexes': [
                    models.Index(fields=['agent', 'status', 'created_at'], name='agents_agen_agent_i_c6460a_idx'),
                    models.Index(fields=['agent', 'redaction_status', 'created_at'], name='agents_agen_agent_i_380a4a_idx'),
                    models.Index(fields=['agent', '-created_at', '-id'], name='agent_run_page_idx'),
                    models.Index(fields=['tenant', 'created_at'], name='agents_agen_tenant__219474_idx'),
                    models.Index(fields=['consumer_tenant', 'caller_subject_hash', 'created_at'], name='agent_run_consumer_idx'),
                    models.Index(fields=['agent', 'run_kind', 'created_at'], name='agent_run_kind_idx'),
                    models.Index(fields=['agent', 'caller_subject_hash', 'caller_hidden_at', 'created_at'], name='agent_run_history_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='AgentDisplayEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seq', models.PositiveIntegerField()),
                ('client_event_id', models.CharField(blank=True, max_length=128, null=True)),
                ('event_type', models.CharField(max_length=96)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('redacted_payload_json', models.JSONField(blank=True, null=True)),
                ('redaction_metadata', models.JSONField(blank=True, default=dict)),
                ('visibility', models.CharField(default='public', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='display_events', to='agents.agent')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_display_events', to='tenancy.tenant')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='agents.agentdisplayrun')),
            ],
            options={
                'indexes': [models.Index(fields=['agent', 'created_at'], name='agents_agen_agent_i_b44efb_idx'), models.Index(fields=['run', 'seq'], name='agents_agen_run_id_185093_idx'), models.Index(fields=['event_type', 'created_at'], name='agents_agen_event_t_db7a63_idx')],
                'constraints': [models.UniqueConstraint(fields=('run', 'seq'), name='unique_agent_display_run_seq'), models.UniqueConstraint(fields=('run', 'client_event_id'), name='unique_agent_run_client_event')],
            },
        ),
        migrations.CreateModel(
            name='AgentDisplayAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(max_length=1024, upload_to=apps.agents.models.agent_display_asset_upload_to)),
                ('content_type', models.CharField(max_length=128)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('sha256', models.CharField(max_length=64)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='display_assets', to='agents.agentdisplayrun')),
            ],
            options={
                'indexes': [models.Index(fields=['run', 'created_at'], name='agent_display_asset_idx')],
            },
        ),
        migrations.CreateModel(
            name='AgentBrowserSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('starting', 'Starting'), ('active', 'Active'), ('closed', 'Closed'), ('failed', 'Failed')], default='starting', max_length=16)),
                ('platform', models.CharField(choices=[('windows', 'Windows'), ('linux', 'Linux'), ('macos', 'macOS')], default='windows', max_length=16)),
                ('remote_pid', models.PositiveIntegerField(blank=True, null=True)),
                ('remote_port', models.PositiveIntegerField(blank=True, null=True)),
                ('profile_path', models.CharField(blank=True, max_length=1024)),
                ('runtime_session_id', models.CharField(blank=True, max_length=64)),
                ('observation_revision', models.PositiveIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=512)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('run', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='browser_session', to='agents.agentdisplayrun')),
            ],
        ),
        migrations.CreateModel(
            name='AgentEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('env', models.CharField(default='prod', max_length=64)),
                ('url', models.URLField(max_length=1024)),
                ('status', models.CharField(default='active', max_length=32)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='agents.agent')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('agent', 'env'), name='unique_agent_endpoint_env')],
            },
        ),
        migrations.CreateModel(
            name='AgentExecutionTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('caller_subject_hash', models.CharField(db_index=True, max_length=64)),
                ('mcp_session_hash', models.CharField(blank=True, max_length=64)),
                ('tool_name', models.CharField(max_length=128)),
                ('request_json', models.JSONField(blank=True, default=dict)),
                ('result_json', models.JSONField(blank=True, default=dict)),
                ('error_code', models.CharField(blank=True, max_length=96)),
                ('status', models.CharField(choices=[('working', 'Working'), ('input_required', 'Input required'), ('cancel_requested', 'Cancellation requested'), ('waiting_for_runtime', 'Waiting for runtime'), ('recovering', 'Recovering'), ('recovery_required', 'Recovery decision required'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='working', max_length=32)),
                ('continuable', models.BooleanField(default=False)),
                ('recovery_protocol', models.PositiveSmallIntegerField(default=0)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_tasks', to='agents.agent')),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='execution_task', to='agents.agentdisplayrun')),
            ],
            options={
                'indexes': [
                    models.Index(fields=['agent', 'caller_subject_hash', 'status'], name='agent_exec_task_subject_idx'),
                    models.Index(fields=['status', 'expires_at'], name='agent_exec_task_expiry_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='AgentFileTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('turn_index', models.PositiveIntegerField(blank=True, null=True)),
                ('caller_subject_hash', models.CharField(max_length=64)),
                ('direction', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=255)),
                ('content_type', models.CharField(default='application/octet-stream', max_length=255)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('received_bytes', models.PositiveBigIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('expected_sha256', models.CharField(blank=True, max_length=64)),
                ('state', models.CharField(default='uploading', max_length=16)),
                ('storage_backend', models.CharField(max_length=32)),
                ('object_key', models.TextField(blank=True)),
                ('computer_revision', models.PositiveIntegerField(default=0)),
                ('lease_id', models.UUIDField(null=True)),
                ('lease_expires_at', models.DateTimeField(null=True)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('source_kind', models.CharField(default='upload', max_length=24)),
                ('source_label', models.CharField(blank=True, max_length=512)),
                ('idempotency_key', models.CharField(blank=True, max_length=128)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.agent')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenancy.project')),
                ('run', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_transfers', to='agents.agentdisplayrun')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant')),
            ],
            options={
                'indexes': [
                    models.Index(fields=['tenant', 'caller_subject_hash', 'state'], name='agents_agen_tenant__57fde0_idx'),
                    models.Index(fields=['state', 'expires_at'], name='agents_agen_state_f32720_idx'),
                ],
                'constraints': [
                    models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('run', 'idempotency_key'), name='agent_run_file_idempotency'),
                ],
            },
        ),
        migrations.CreateModel(
            name='AgentFilePart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('index', models.IntegerField()),
                ('object_key', models.TextField()),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='agents.agentfiletransfer')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('transfer', 'index'), name='unique_agent_file_part')],
            },
        ),
        migrations.CreateModel(
            name='AgentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'Info'), ('error', 'Error')], default='info', max_length=16)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='agents.agent')),
                ('deployment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='agents.agentdeployment')),
            ],
            options={
                'indexes': [models.Index(fields=['agent', 'created_at'], name='agents_agen_agent_i_bfe9af_idx'), models.Index(fields=['agent', '-created_at', '-id'], name='agent_log_page_idx')],
            },
        ),
        migrations.CreateModel(
            name='AgentMemoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('deleted', 'Deleted')], default='active', max_length=32)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('memory_type', models.CharField(choices=[('fact', 'Fact'), ('preference', 'Preference'), ('workflow', 'Workflow'), ('domain_knowledge', 'Domain knowledge'), ('user_profile', 'User profile')], default='fact', max_length=64)),
                ('content_text', models.TextField(blank=True)),
                ('content_json', models.JSONField(blank=True, default=dict)),
                ('scope', models.CharField(choices=[('caller', 'Caller'), ('agent_global', 'Agent global'), ('developer_only', 'Developer only')], default='caller', max_length=32)),
                ('caller_subject_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('source_event_ids', models.JSONField(blank=True, default=list)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('confidence', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=5)),
                ('sensitivity_level', models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('confidential', 'Confidential'), ('restricted', 'Restricted')], default='internal', max_length=32)),
                ('consent_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('revoked', 'Revoked')], default='pending', max_length=32)),
                ('license_status', models.CharField(choices=[('unknown', 'Unknown'), ('internal', 'Internal'), ('approved', 'Approved')], default='unknown', max_length=32)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_memory_items', to=settings.AUTH_USER_MODEL)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_items', to='agents.agent')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_memory_items', to='tenancy.project')),
                ('source_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memory_items', to='agents.agentdisplayrun')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_memory_items', to='tenancy.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['agent', '-created_at', '-id'], name='agent_memory_page_idx'), models.Index(fields=['tenant', 'agent', 'status', 'created_at'], name='agents_agen_tenant__c98979_idx'), models.Index(fields=['tenant', 'memory_type', 'status', 'created_at'], name='agents_agen_tenant__749347_idx'), models.Index(fields=['tenant', 'consent_status', 'license_status'], name='agents_agen_tenant__0fa5d7_idx')],
            },
        ),
        migrations.CreateModel(
            name='AgentMobileBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('deleted', 'Deleted')], default='active', max_length=32)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('caller_subject_hash', models.CharField(db_index=True, max_length=64)),
                ('caller_principal_type', models.CharField(max_length=32)),
                ('is_default', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_bindings', to='agents.agent')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_mobile_bindings', to='tenancy.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_mobile_bindings', to='tenancy.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='agentdisplayrun',
            name='mobile_binding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='display_runs', to='agents.agentmobilebinding'),
        ),
        migrations.CreateModel(
            name='AgentMobileGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('deleted', 'Deleted')], default='active', max_length=32)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('caller_subject_hash', models.CharField(db_index=True, max_length=64)),
                ('caller_principal_type', models.CharField(max_length=32)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('granted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_grants', to='agents.agent')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_mobile_grants', to='tenancy.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_mobile_grants', to='tenancy.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'agent', 'caller_subject_hash', 'status'], name='agent_mobile_grant_subj_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('project__isnull', True)), fields=('tenant', 'agent', 'caller_subject_hash'), name='uniq_agent_mobile_grant_ten'), models.UniqueConstraint(condition=models.Q(('project__isnull', False)), fields=('tenant', 'project', 'agent', 'caller_subject_hash'), name='uniq_agent_mobile_grant_proj')],
            },
        ),
        migrations.CreateModel(
            name='AgentMobileLease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('deleted', 'Deleted')], default='active', max_length=32)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_lease', to='agents.agentdisplayrun')),
            ],
        ),
        migrations.CreateModel(
            name='AgentOutputArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('deleted', 'Deleted')], default='active', max_length=32)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('turn_index', models.PositiveIntegerField(blank=True, null=True)),
                ('workspace_path', models.CharField(max_length=1024)),
                ('computer_revision', models.PositiveIntegerField(default=0)),
                ('original_file_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=128)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('producer_step', models.CharField(blank=True, max_length=255)),
                ('license_status', models.CharField(choices=[('unknown', 'Unknown'), ('internal', 'Internal'), ('approved', 'Approved')], default='internal', max_length=32)),
                ('scan_status', models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('policy_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('blocked', 'Blocked')], default='pending', max_length=32)),
                ('scan_metadata', models.JSONField(blank=True, default=dict)),
                ('snapshot_storage_backend', models.CharField(blank=True, max_length=32)),
                ('snapshot_object_key', models.CharField(blank=True, max_length=1024)),
                ('snapshot_status', models.CharField(default='pending', max_length=32)),
                ('snapshot_error', models.CharField(blank=True, max_length=1024)),
                ('snapshotted_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output_artifacts', to='agents.agent')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_output_artifacts', to='tenancy.project')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output_artifacts', to='agents.agentdisplayrun')),
                ('source_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='output_artifacts', to='agents.agentdisplayevent')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_output_artifacts', to='tenancy.tenant')),
            ],
            options={
                'indexes': [
                    models.Index(fields=['tenant', 'agent', 'run', 'status'], name='agents_agen_tenant__2e7482_idx'),
                    models.Index(fields=['run', '-created_at', '-id'], name='agent_output_page_idx'),
                    models.Index(fields=['tenant', 'scan_status', 'policy_status'], name='agents_agen_tenant__11e7c7_idx'),
                ],
                'constraints': [
                    models.UniqueConstraint(fields=('run', 'computer_revision', 'workspace_path'), name='unique_agent_run_output_revision'),
                ],
            },
        ),
        migrations.AddField(
            model_name='agentfiletransfer',
            name='artifact',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agentoutputartifact'),
        ),
        migrations.CreateModel(
            name='AgentProjectContextGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('deleted', 'Deleted')], default='active', max_length=32)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('caller_principal_type', models.CharField(max_length=32)),
                ('caller_subject_hash', models.CharField(db_index=True, max_length=64)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_context_grants', to='agents.agent')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_context_grants', to='tenancy.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_project_context_grants', to='tenancy.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'project', 'caller_subject_hash', 'status'], name='agent_proj_ctx_grant_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('tenant', 'project', 'agent', 'caller_subject_hash'), name='unique_active_agent_project_context_grant')],
            },
        ),
        migrations.CreateModel(
            name='AgentResourceConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('deleted', 'Deleted')], default='active', max_length=32)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('cpu', models.CharField(max_length=32)),
                ('memory', models.CharField(max_length=32)),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resource_config', to='agents.agent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AgentRunCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=128)),
                ('data_json', models.JSONField(blank=True, default=dict)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoint', to='agents.agentdisplayrun')),
            ],
        ),
        migrations.CreateModel(
            name='AgentRunComputerAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField()),
                ('computer_name', models.CharField(blank=True, max_length=128)),
                ('workspace_root', models.CharField(blank=True, max_length=1024)),
                ('output_root', models.CharField(blank=True, max_length=1024)),
                ('after_event_seq', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('binding', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agentcomputerbinding')),
                ('browser_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agentbrowsersession')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computer_attachments', to='agents.agentdisplayrun')),
            ],
        ),
        migrations.CreateModel(
            name='AgentRunFollowUp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('fingerprint', models.CharField(max_length=64)),
                ('mode', models.CharField(max_length=16)),
                ('turn_index', models.PositiveIntegerField()),
                ('dispatched_turn', models.PositiveIntegerField(blank=True, null=True)),
                ('content', models.TextField()),
                ('position', models.PositiveBigIntegerField(default=0)),
                ('attachment_manifest', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(default='pending', max_length=24)),
                ('code', models.CharField(blank=True, max_length=64)),
                ('encrypted_authority', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='agents.agentdisplayrun')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'mode', 'created_at'], name='agent_follow_up_pending')],
                'constraints': [models.UniqueConstraint(fields=('run', 'idempotency_key'), name='agent_follow_up_idempotency')],
            },
        ),
        migrations.CreateModel(
            name='AgentRunInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=128)),
                ('kind', models.CharField(choices=[('text', 'Text'), ('confirm', 'Confirm'), ('select', 'Select')], default='text', max_length=16)),
                ('prompt', models.TextField(blank=True)),
                ('choices_json', models.JSONField(blank=True, default=list)),
                ('response_json', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('answered', 'Answered'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='agents.agentdisplayrun')),
            ],
            options={
                'indexes': [models.Index(fields=['run', 'status', 'created_at'], name='agent_run_interaction_idx')],
                'constraints': [models.UniqueConstraint(fields=('run', 'key'), name='unique_agent_run_interaction_key')],
            },
        ),
        migrations.CreateModel(
            name='AgentRunMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('turn_index', models.PositiveIntegerField(blank=True, null=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=16)),
                ('content', models.TextField()),
                ('content_blocks', models.JSONField(blank=True, default=list)),
                ('source_message_id', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='agents.agentdisplayrun')),
            ],
            options={
                'indexes': [models.Index(fields=['run', 'created_at'], name='agent_run_message_idx')],
                'constraints': [models.UniqueConstraint(fields=('run', 'sequence'), name='unique_agent_run_message_seq'), models.UniqueConstraint(condition=models.Q(('source_message_id', ''), _negated=True), fields=('run', 'source_message_id'), name='unique_agent_run_source_message')],
            },
        ),
        migrations.CreateModel(
            name='AgentRunOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('turn_index', models.PositiveIntegerField()),
                ('sequence', models.PositiveIntegerField()),
                ('recovery_generation', models.PositiveSmallIntegerField(default=0)),
                ('operation_type', models.CharField(max_length=96)),
                ('request_digest', models.CharField(max_length=64)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('prepared', 'Prepared'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('outcome_unknown', 'Outcome unknown')], default='prepared', max_length=24)),
                ('result_json', models.JSONField(blank=True, default=dict)),
                ('result_ciphertext', models.TextField(blank=True)),
                ('error_code', models.CharField(blank=True, max_length=96)),
                ('can_reconcile', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='agents.agentdisplayrun')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='agents.agentexecutiontask')),
            ],
            options={
                'indexes': [models.Index(fields=['task', 'status'], name='agent_run_op_task_status_idx'), models.Index(fields=['run', 'turn_index', 'sequence'], name='agent_run_op_order_idx')],
                'constraints': [models.UniqueConstraint(fields=('run', 'turn_index', 'sequence'), name='agent_run_operation_sequence_unique')],
            },
        ),
        migrations.CreateModel(
            name='AgentRuntimeDeployment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('runtime_kind', models.CharField(choices=[('docker', 'Docker'), ('openwrt_ipv6', 'OpenWrt IPv6'), ('openwrt_relay', 'OpenWrt Relay')], default='docker', max_length=32)),
                ('env', models.CharField(default='prod', max_length=64)),
                ('status', models.CharField(choices=[('deploying', 'Deploying'), ('active', 'Active'), ('stopped', 'Stopped'), ('failed', 'Failed'), ('deleted', 'Deleted')], default='deploying', max_length=32)),
                ('container_id', models.CharField(blank=True, max_length=128)),
                ('docker_lifecycle', models.JSONField(blank=True, default=dict)),
                ('internal_mcp_url', models.URLField(blank=True, max_length=1024)),
                ('health_status', models.CharField(choices=[('unknown', 'Unknown'), ('healthy', 'Healthy'), ('degraded', 'Degraded'), ('unhealthy', 'Unhealthy')], default='unknown', max_length=32)),
                ('last_error', models.CharField(blank=True, max_length=1024)),
                ('workspace_root', models.CharField(blank=True, max_length=1024)),
                ('workspace_access_mode', models.CharField(choices=[('read_only', 'Read only'), ('read_write', 'Read/write')], default='read_only', max_length=32)),
                ('workspace_token', models.CharField(blank=True, max_length=128)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runtime_deployments', to='agents.agent')),
                ('agent_deployment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runtime_deployments', to='agents.agentdeployment')),
                ('deployed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_runtime_deployments', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_runtime_deployments', to='tenancy.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_runtime_deployments', to='tenancy.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='AgentRecoveryAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('turn_index', models.PositiveIntegerField()),
                ('attempt', models.PositiveSmallIntegerField()),
                ('reason', models.CharField(max_length=96)),
                ('status', models.CharField(default='waiting_for_runtime', max_length=32)),
                ('agent_version', models.CharField(blank=True, max_length=32)),
                ('tool_contract_digest', models.CharField(blank=True, max_length=64)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_attempts', to='agents.agentexecutiontask')),
                ('runtime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovery_attempts', to='agents.agentruntimedeployment')),
            ],
            options={
                'indexes': [models.Index(fields=['task', 'status'], name='agent_recovery_task_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('task', 'turn_index', 'attempt'), name='agent_recovery_attempt_unique')],
            },
        ),
        migrations.AddField(
            model_name='agentoutputartifact',
            name='runtime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='output_artifacts', to='agents.agentruntimedeployment'),
        ),
        migrations.CreateModel(
            name='AgentMCPSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('caller_subject_hash', models.CharField(db_index=True, max_length=64)),
                ('external_session_hash', models.CharField(max_length=64, unique=True)),
                ('internal_session_id', models.CharField(max_length=512)),
                ('client_capabilities_json', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_sessions', to='agents.agent')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_mcp_sessions', to='tenancy.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_mcp_sessions', to='tenancy.tenant')),
                ('runtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_sessions', to='agents.agentruntimedeployment')),
            ],
            options={
                'indexes': [models.Index(fields=['agent', 'caller_subject_hash', 'expires_at'], name='agent_mcp_session_subject_idx')],
            },
        ),
        migrations.AddField(
            model_name='agentexecutiontask',
            name='runtime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_tasks', to='agents.agentruntimedeployment'),
        ),
        migrations.AddField(
            model_name='agentdisplayrun',
            name='runtime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='display_runs', to='agents.agentruntimedeployment'),
        ),
        migrations.CreateModel(
            name='AgentRuntimeImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('deleted', 'Deleted')], default='active', max_length=32)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('image_ref', models.CharField(max_length=512)),
                ('image_digest', models.CharField(blank=True, max_length=128)),
                ('artifact_path', models.CharField(blank=True, max_length=1024)),
                ('registry_secret_ref', models.CharField(blank=True, max_length=255)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runtime_images', to='agents.agent')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_agent_runtime_images', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_runtime_images', to='tenancy.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_runtime_images', to='tenancy.tenant')),
            ],
            options={
                'indexes': [
                    models.Index(fields=['tenant', 'agent', 'status'], name='agents_agen_tenant__5a95b8_idx'),
                    models.Index(fields=['tenant', 'project', 'status'], name='agents_agen_tenant__4152e2_idx'),
                ],
            },
        ),
        migrations.AddField(
            model_name='agentruntimedeployment',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='runtime_deployments', to='agents.agentruntimeimage'),
        ),
        migrations.CreateModel(
            name='AgentPythonBuild',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(max_length=128)),
                ('source', models.TextField()),
                ('requirements', models.TextField(blank=True)),
                ('source_sha256', models.CharField(max_length=64)),
                ('entrypoint', models.CharField(max_length=64)),
                ('framework', models.CharField(max_length=32)),
                ('base_image', models.CharField(max_length=512)),
                ('encrypted_secrets', models.TextField(blank=True)),
                ('status', models.CharField(default='queued', max_length=24)),
                ('stage', models.CharField(default='queued', max_length=32)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.CharField(blank=True, max_length=512)),
                ('diagnostics', models.JSONField(default=list)),
                ('dependency_lock', models.JSONField(default=list)),
                ('tool_count', models.PositiveIntegerField(default=0)),
                ('worker_id', models.CharField(blank=True, max_length=128)),
                ('target_host', models.CharField(default='local', max_length=128)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='python_builds', to='agents.agent')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('image', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='python_build', to='agents.agentruntimeimage')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'created_at'], name='agent_python_build_queue')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'running'])), fields=('agent',), name='agent_one_pending_python_build')],
            },
        ),
        migrations.AddField(
            model_name='agent',
            name='current_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='agents.agentruntimeimage'),
        ),
        migrations.CreateModel(
            name='AgentRuntimeInvocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tool_name', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], max_length=32)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('turn_index', models.PositiveIntegerField(default=1)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('execution_profile_id', models.CharField(blank=True, max_length=64)),
                ('execution_model', models.CharField(blank=True, max_length=128)),
                ('reasoning_effort', models.CharField(blank=True, max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_runtime_invocations', to=settings.AUTH_USER_MODEL)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runtime_invocations', to='agents.agent')),
                ('deployment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invocations', to='agents.agentruntimedeployment')),
                ('display_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runtime_invocations', to='agents.agentdisplayrun')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_runtime_invocations', to='tenancy.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_runtime_invocations', to='tenancy.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'agent', 'created_at'], name='agents_agen_tenant__5561b4_idx'), models.Index(fields=['tenant', 'status', 'created_at'], name='agents_agen_tenant__b14538_idx'), models.Index(fields=['agent', 'tool_name', 'display_run'], name='agent_inv_tool_run_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('display_run__isnull', False)), fields=('display_run', 'turn_index'), name='unique_agent_invocation_run_turn')],
            },
        ),
        migrations.CreateModel(
            name='AgentModelUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('turn_index', models.PositiveIntegerField(default=1)),
                ('event_id', models.CharField(max_length=128)),
                ('profile_id', models.CharField(blank=True, max_length=64)),
                ('model', models.CharField(max_length=128)),
                ('input_tokens', models.PositiveBigIntegerField(default=0)),
                ('output_tokens', models.PositiveBigIntegerField(default=0)),
                ('cached_input_tokens', models.PositiveBigIntegerField(default=0)),
                ('reasoning_tokens', models.PositiveBigIntegerField(default=0)),
                ('context_window', models.PositiveBigIntegerField()),
                ('primary', models.BooleanField(default=True)),
                ('source', models.CharField(default='sdk', max_length=32)),
                ('payload_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_usage', to='agents.agentdisplayrun')),
                ('invocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_usage', to='agents.agentruntimeinvocation')),
            ],
            options={
                'indexes': [models.Index(fields=['run', 'turn_index', 'created_at'], name='agent_usage_run_turn_idx')],
                'constraints': [models.UniqueConstraint(fields=('run', 'event_id'), name='unique_agent_usage_event')],
            },
        ),
        migrations.CreateModel(
            name='AgentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.CharField(max_length=32)),
                ('commit_id', models.CharField(blank=True, max_length=128)),
                ('artifact_metadata', models.JSONField(blank=True, default=dict)),
                ('workspace_capabilities', models.JSONField(blank=True, default=list)),
                ('mobile_requirement', models.CharField(choices=[('required', 'Required'), ('optional', 'Optional'), ('disabled', 'Disabled')], default='disabled', max_length=16)),
                ('mobile_capabilities', models.JSONField(blank=True, default=list)),
                ('tool_runtime_policy', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('published', 'Published'), ('rolled_back', 'Rolled back')], default='published', max_length=32)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='agents.agent')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_agent_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['agent', 'status', 'created_at'], name='agents_agen_agent_i_68c362_idx')],
                'constraints': [models.UniqueConstraint(fields=('agent', 'version'), name='unique_agent_version')],
            },
        ),
        migrations.AddField(
            model_name='agentruntimeimage',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runtime_images', to='agents.agentversion'),
        ),
        migrations.AddField(
            model_name='agentdeployment',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployments', to='agents.agentversion'),
        ),
        migrations.CreateModel(
            name='AgentWorkspaceGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('deleted', 'Deleted')], default='active', max_length=32)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('caller_subject_hash', models.CharField(db_index=True, max_length=64)),
                ('caller_principal_type', models.CharField(max_length=32)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('granted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_grants', to='agents.agent')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_workspace_grants', to='tenancy.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_workspace_grants', to='tenancy.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'agent', 'caller_subject_hash', 'status'], name='agent_ws_grant_subject_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('project__isnull', True)), fields=('tenant', 'agent', 'caller_subject_hash'), name='unique_agent_workspace_grant_tenant'), models.UniqueConstraint(condition=models.Q(('project__isnull', False)), fields=('tenant', 'project', 'agent', 'caller_subject_hash'), name='unique_agent_workspace_grant_project')],
            },
        ),
        migrations.CreateModel(
            name='EdgeAgentRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('deleted', 'Deleted')], default='active', max_length=32)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('origin', models.CharField(max_length=512)),
                ('route_id', models.CharField(max_length=128)),
                ('protocols', models.JSONField(blank=True, default=list)),
                ('capabilities', models.JSONField(blank=True, default=list)),
                ('mcp_tools', models.JSONField(blank=True, default=list)),
                ('binding_mode', models.CharField(choices=[('manual', 'Manual'), ('managed', 'OpenWrt managed'), ('suppressed', 'Managed binding suppressed')], default='manual', max_length=16)),
                ('managed_agent_name', models.CharField(blank=True, max_length=255)),
                ('manifest_digest', models.CharField(blank=True, max_length=64)),
                ('computer_requirement', models.CharField(blank=True, choices=[('required', 'Required'), ('optional', 'Optional'), ('disabled', 'Disabled')], default='', max_length=16)),
                ('workspace_capabilities', models.JSONField(blank=True, default=list)),
                ('mobile_requirement', models.CharField(blank=True, choices=[('required', 'Required'), ('optional', 'Optional'), ('disabled', 'Disabled')], default='', max_length=16)),
                ('mobile_capabilities', models.JSONField(blank=True, default=list)),
                ('transport', models.CharField(choices=[('direct_ipv6', 'Direct IPv6'), ('relay', 'Relay')], default='direct_ipv6', max_length=32)),
                ('ipv6_address', models.GenericIPAddressField(blank=True, null=True, protocol='IPv6')),
                ('port', models.PositiveIntegerField(blank=True, null=True)),
                ('path', models.CharField(blank=True, default='', max_length=255)),
                ('scheme', models.CharField(blank=True, default='', max_length=16)),
                ('tls_server_name', models.CharField(blank=True, max_length=253)),
                ('ca_bundle_id', models.CharField(blank=True, max_length=128)),
                ('relay_id', models.CharField(blank=True, max_length=64)),
                ('relay_router_id', models.CharField(blank=True, max_length=64)),
                ('relay_assignment_id', models.CharField(blank=True, max_length=64)),
                ('generation', models.PositiveBigIntegerField(default=1)),
                ('lease_expires_at', models.DateTimeField()),
                ('last_renewed_at', models.DateTimeField()),
                ('last_probe_at', models.DateTimeField(blank=True, null=True)),
                ('health_status', models.CharField(choices=[('unknown', 'Unknown'), ('healthy', 'Healthy'), ('degraded', 'Degraded'), ('unhealthy', 'Unhealthy')], default='unknown', max_length=32)),
                ('agent', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edge_registration', to='agents.agent')),
            ],
        ),
        migrations.AddField(
            model_name='agentruntimedeployment',
            name='edge_registration',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='runtime_deployment', to='agents.edgeagentregistration'),
        ),
        migrations.CreateModel(
            name='AgentRunContextGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('encrypted_context', models.TextField()),
                ('expires_at', models.DateTimeField()),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_context_grants', to='agents.agent')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context_grants', to='agents.agentdisplayrun')),
                ('edge_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_context_grants', to='agents.edgeagentregistration')),
            ],
            options={
                'indexes': [models.Index(fields=['run', 'expires_at'], name='agent_ctx_run_exp_idx'), models.Index(fields=['edge_registration', 'expires_at'], name='agent_ctx_edge_exp_idx')],
            },
        ),
        migrations.CreateModel(
            name='EdgeNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('deleted', 'Deleted')], default='active', max_length=32)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('owner_subject_type', models.CharField(blank=True, max_length=32)),
                ('owner_subject_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('router_id', models.CharField(max_length=128)),
                ('domain_id', models.CharField(max_length=253)),
                ('display_name', models.CharField(max_length=255)),
                ('device_token_hash', models.CharField(max_length=64, unique=True)),
                ('device_cert_thumbprint', models.CharField(blank=True, max_length=64)),
                ('pending_device_cert_thumbprint', models.CharField(blank=True, max_length=64)),
                ('pending_device_cert_expires_at', models.DateTimeField(blank=True, null=True)),
                ('connection_status', models.CharField(choices=[('pending', 'Pending'), ('online', 'Online'), ('degraded', 'Degraded'), ('offline', 'Offline'), ('revoked', 'Revoked')], default='pending', max_length=32)),
                ('presence_protocol_version', models.PositiveSmallIntegerField(default=0)),
                ('last_presence_at', models.DateTimeField(blank=True, null=True)),
                ('presence_expires_at', models.DateTimeField(blank=True, null=True)),
                ('connection_status_reason', models.CharField(default='pending_heartbeat', max_length=48)),
                ('registration_diagnostic', models.JSONField(blank=True, default=dict)),
                ('ipv6_mode', models.CharField(choices=[('routed_prefix', 'Routed prefix'), ('upstream_relay', 'Upstream relay'), ('agent_owned', 'Agent owned')], default='routed_prefix', max_length=32)),
                ('connectivity_mode', models.CharField(choices=[('direct_ipv6', 'Direct IPv6'), ('relay', 'Relay')], default='direct_ipv6', max_length=32)),
                ('relay_id', models.CharField(blank=True, max_length=64)),
                ('relay_assignment_id', models.CharField(blank=True, max_length=64)),
                ('relay_lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('software_version', models.CharField(blank=True, max_length=64)),
                ('capabilities', models.JSONField(blank=True, default=dict)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edge_nodes', to='tenancy.project')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_edge_nodes', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edge_nodes', to='tenancy.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'connection_status'], name='agents_edge_tenant_conn_idx'), models.Index(fields=['tenant', 'project', 'status'], name='agents_edge_tenant_proj_idx'), models.Index(fields=['tenant', 'owner_subject_hash', 'status'], name='agents_edge_owner_status_idx'), models.Index(fields=['status', 'presence_expires_at'], name='agents_edge_presence_exp_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'router_id'), name='unique_tenant_edge_router')],
            },
        ),
        migrations.AddField(
            model_name='edgeagentregistration',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_registrations', to='agents.edgenode'),
        ),
        migrations.CreateModel(
            name='EdgePairingCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_subject_type', models.CharField(blank=True, max_length=32)),
                ('owner_subject_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_edge_pairing_codes', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edge_pairing_codes', to='tenancy.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edge_pairing_codes', to='tenancy.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'expires_at'], name='agents_pair_tenant_exp_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='edgeagentregistration',
            index=models.Index(fields=['node', 'status', 'lease_expires_at'], name='agents_edge_reg_lease_idx'),
        ),
        migrations.AddIndex(
            model_name='edgeagentregistration',
            index=models.Index(fields=['agent', 'status'], name='agents_edge_reg_agent_idx'),
        ),
        migrations.AddConstraint(
            model_name='edgeagentregistration',
            constraint=models.UniqueConstraint(fields=('node', 'origin'), name='unique_edge_node_agent_origin'),
        ),
    ]
